build:
  stage: build
  variables:
    IMAGE_SRV_NAME: $CI_PROJECT_NAME
  image:
    name: gcr.io/kaniko-project/executor:v1.10.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${REGISTRY_USER}" "${REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - VERSION=$CI_COMMIT_TAG
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/deployment/common.dockerfile"
      --destination "${REGISTRY}/alerta/${IMAGE_SRV_NAME}:${VERSION}"
      --destination "${REGISTRY}/alerta/${IMAGE_SRV_NAME}:latest"
      --build-arg "VERSION=$VERSION"
  rules:
    - if: $CI_COMMIT_TAG
